global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rules-engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 5s
    scrape_timeout: 5s
